version: "3"
services:
  api:
    image: mhart/alpine-node:14
    container_name: rosters-ninja-api
    restart: always
    volumes:
    - ./packages/api:/usr/app
    - ./packages/api/node_modules:/usr/app/node_modules
    ports:
    - 8080:8080
    working_dir: /usr/app
    command: npm start
  web:
    image: mhart/alpine-node:14
    container_name: rosters-ninja-web
    restart: always
    volumes:
    - ./packages/web:/usr/app
    - ./packages/web/node_modules:/usr/web/node_modules
    ports:
    - 3000:3000
    working_dir: /usr/app
    command: npm start
    links:
      - api
