version: "3"
services:
  api:
    image: mhart/alpine-node:14
    restart: always
    volumes:
    - ./packages/api:/usr/app
    - ./packages/api/node_modules:/usr/app/node_modules
    ports:
    - 8080:8080
    working_dir: /usr/app
    command: npm start